version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: user-management-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      MONGO_URI: mongodb://root:example@mongo:27017/userDB?authSource=admin
      JWT_SECRET: yourSecretKey
      JWT_EXPIRES_IN: 1h
    depends_on:
      - mongo

volumes:
  mongo-data:
